version: '3.8'

services:

  mysql:
    image: mysql:8.0.13
    container_name: mysql-rockola
    hostname: mysql-rockola
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - rockola-network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin-rockola
  #   hostname: phpmyadmin
  #   restart: always
  #   ports:
  #     - "${PHPMYADMIN_PORT}:80"
  #   environment:
  #     PMA_HOST: ${DB_HOST}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #   depends_on:
  #     - mysql
  #   networks:
  #     - wordpress-network

networks:
  rockola-network:
    external: true