version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gestion-rockola
    working_dir: /var/www/html/
    restart: always
    container_name: gestion-rockola
    hostname: gestion-rockola
    ports:
      - "${GESTION_PORT}:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - rockola-network

networks:
  rockola-network:
    external: true